config/routes.rb
Pianizm50::Application.routes.draw do
  get "song/add"

  match "song/showAddSongForm" => "song#showAddSongForm"
  match "add" =>  "song#add"
  match "testV" =>  "testV#testV"

  get "song/view"

end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
  attr_accessible :name
end

app/models/tune.rb
class Tune < ActiveRecord::Base
  attr_accessible :author, :name, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/song_controller.rb
class SongController < ApplicationController
  def add
    @tune =  Tune.new(params[:tune])
    if @tune.save
      @error = "There are no available doctors for your input"
      #redirect_to  mono_path
    else
      @error = "There are no available offices for your input"
      #redirect_to barro_path
    end
  end

  def showAddSongForm
    @tune = Tune.new
  end

  def view
    @tunes = Tune.all
  end
end

app/controllers/test_v_controller.rb
class TestVController < ApplicationController
  def testV

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/test_v_helper.rb
module TestVHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pianizm50</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/song/add.html.erb
monisimo
I just deployed again!

app/views/song/showAddSongForm.html.erb
<%= form_for @tune , :url => add_path do |f| %>
    <%= f.text_field :name %>
    <%= f.text_area :url  , :size => "60x12" %>
    <%= f.text_area :author %>
    <%= f.submit "Create" %>
<% end %>

app/views/song/view.html.erb
que nivel  2
<table>
  <% @tunes.each do |song| %>
      <tr>
        <td style = "color:red ; " ><%= song[:name] %></td>
        <td style = "color: blue ; " ><%= song[:url]  %>
        <td style = "color: blue ; " ><%= song[:info]  %>
      </tr>
  <% end %>
</table>

app/views/test_v/testV.html.erb
hello covas